### ISSUE TITLE
Documentation for local installation provides wrong link for rbenv

### ISSUE THREAD

**Issue by sthinbetween** [consul/docs#115]

**Comment by sthinbetween** [comment]
https://docs.consulproject.org/docs/english-documentation/introduction/local_installation/ubuntu

Command for rbenv-installer is not right and should be 
wget -q https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer -O- | bash

**Comment by javierm** [comment]
Hi, @sthinbetween :smile:.

Thanks for reporting! We're about to make this repository read-only since from now on we'll be using [our GitBook page](https://docs.consuldemocracy.org/tech_docs/) to do the changes.

I've just applied the fix on the [Ubuntu installation documentation on the new documentation site](https://docs.consuldemocracy.org/tech_docs/introduction-1/local_installation/ubuntu).
