### ISSUE TITLE
German documentation

### ISSUE THREAD

**Issue by linux-lukas** [consul/docs#120]
### A. Problem / Goal

Public administration is lagging behind in the area of digitisation of administration, especially when it comes to open source solutions, also because these usually only offer English documentation, but many know little or no English. This is a clear barrier.

The goal is to make it easier for people in German-speaking administrations who speak little or no English or Spanish to set up their own Consul instance.

### B. Solution 

I add a German translation based on the English documentation with pull request https://github.com/consul/docs/pull/121 . :)

### C. Alternatives

Few German administrations will opt for Consul.

**Comment by javierm** [comment]
As mentioned in #121, we're about to make this repository read-only since from now on we'll be using [our GitBook page](https://docs.consuldemocracy.org/tech_docs/) to do the changes.

So I'm closing this issue.

The new platform will make it easier to add new languages, so if you're still interested in helping with the German documentation, please [contact the Consul Democracy Foundation](http://consuldemocracy.org/en/index.html#contact).
