### ISSUE TITLE
Detail fork collaboration through github

### ISSUE THREAD

**Issue by bertocq** [consul/docs#34]
On a fork that has their own changes (for their custom needs) contributing back to Consul can be complicated (because the git diff will show more changes than a PR for an specific topic would need)

We need to clearly state on the fork update/contribution section steps to do it clean. 

On the current documentation we've to change `consul_pull` for `upstream`.

The `upstream` branch:
- Should not be deleted ever.
- Should act as a mirror of consul#master branch, keeping it  updated as often as possible.
- Should be used to do internal PR's against the fork's `master` to get the fork updated with latest consul changes.
- Should be used to create a feature branch off it when the fork wants to contribute something back to consul, and after adding some commits a PR should be created from that feature branch against consul#master, that way we can guarantee only those intented changes will be contributed.

Any change specific to the fork should be done on its own `master` branch merging feature branches that start off its `master` branch.

**Comment by javierm** [comment]
While I understand the point, IMHO a detailed documentation about how to handle branches in order to open a pull request would be a bit too much :thinking:.

To say it blunty, if someone doesn't know about this stuff, it's likely their pull request will contain commits which will be very hard to review.
