### ISSUE TITLE
Documentation for Apache

### ISSUE THREAD

**Issue by z37a** [consul/docs#97]
It's possible to add documentation to use with Apache webservers?
Es posible añadir documentación para usar con Apache Webserver?

**Comment by javierm** [comment]
@z37a I'm afraid we don't have enough experience with Apache+Puma to provide a proper documentation (in my case, that's actually a combination I've never used). We don't even document how to setup Nginx+Puma because [our installer](https://github.com/consul/installer) takes care of that and so manual setups shouldn't be needed.

CONSUL is basically a Rails application using Puma, so I can only recommend you to search for documentation about using Apache with Puma or asking one of their communities.

Sorry I can't be more helpful here! :pray:

By the way, if you manage to set it up, it would be great if you could open a pull request documenting what you've done or, even better, adding Apache support to the installer.

**Comment by javierm** [comment]
Hi, @z37a :smile:.

We're about to make this repository read-only since from now on we'll be using [our GitBook page](https://docs.consuldemocracy.org/tech_docs/) to do the changes.

So I'm closing this issue. Sorry we still don't have enough knowledge about Apache in order to document it! If you'd like to help in that regard, please [contact the Consul Democracy Foundation](http://consuldemocracy.org/en/index.html#contact).
